# -*- coding: utf-8 -*-
"""teslaaa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtVXac-Z8VtFZv2l0XGBSFYzgMI7ouJn
"""

import streamlit as st

import numpy as np
import pandas as pd

import plotly.graph_objects as go

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, LSTM, SimpleRNN
from tensorflow.keras.callbacks import EarlyStopping

import keras_tuner as kt

import warnings
warnings.filterwarnings("ignore")

pip install tensorflow

!pip install tensorflow keras-tuner -q

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("TSLA.csv")

df['MA_50'] = df['Close'].rolling(50).mean()
df['MA_200'] = df['Close'].rolling(200).mean()

print("Shape:", df.shape)

df.info()

df.describe()

df.isnull().sum()

df['Date'] = pd.to_datetime(df['Date'])

df.set_index('Date', inplace=True)

df.head()

plt.figure(figsize=(15,5))

plt.plot(df['Close'])

plt.title("Tesla Closing Price")

plt.show()

plt.figure(figsize=(15,5))

plt.plot(df['Volume'])

plt.title("Tesla Volume")

plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(df.corr(), annot=True)

plt.show()

data = df[['Close']]

scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(data)

def create_dataset(dataset, timestep):

    X = []
    y = []

    for i in range(len(dataset)-timestep):

        X.append(dataset[i:i+timestep,0])

        y.append(dataset[i+timestep,0])

    return np.array(X), np.array(y)

timestep = 60

X, y = create_dataset(
    scaled_data,
    timestep
)

train_size = int(len(X)*0.80)

X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

X_train = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

print(X_train.shape)
print(X_test.shape)

rnn_model = Sequential()

rnn_model.add(
    SimpleRNN(
        50,
        return_sequences=True,
        input_shape=(60,1)
    )
)

rnn_model.add(Dropout(0.2))

rnn_model.add(SimpleRNN(50))

rnn_model.add(Dropout(0.2))

rnn_model.add(Dense(1))

rnn_model.compile(
    optimizer='adam',
    loss='mse'
)

rnn_model.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

history_rnn = rnn_model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test,y_test),
    callbacks=[early_stop]
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

history_rnn = rnn_model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test,y_test),
    callbacks=[early_stop]
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

lstm_model = Sequential()

lstm_model.add(
    LSTM(
        50,
        return_sequences=True,
        input_shape=(60,1)
    )
)

lstm_model.add(Dropout(0.2))

lstm_model.add(LSTM(50))

lstm_model.add(Dropout(0.2))

lstm_model.add(Dense(1))

lstm_model.compile(
    optimizer='adam',
    loss='mse'
)

lstm_model.summary()

history_lstm = lstm_model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test,y_test),
    callbacks=[early_stop]
)

lstm_model.save("Tesla_LSTM_Model.h5")

!ls -lh Tesla_LSTM_Model.h5

rnn_pred = rnn_model.predict(X_test)

rnn_pred = scaler.inverse_transform(rnn_pred)

actual_rnn = scaler.inverse_transform(
    y_test.reshape(-1,1)
)

rnn_pred = rnn_model.predict(X_test)

rnn_pred = scaler.inverse_transform(rnn_pred)

actual_rnn = scaler.inverse_transform(
    y_test.reshape(-1,1)
)

lstm_pred = lstm_model.predict(X_test)

lstm_pred = scaler.inverse_transform(lstm_pred)

actual_lstm = scaler.inverse_transform(
    y_test.reshape(-1,1)
)

rnn_mse = mean_squared_error(
    actual_rnn,
    rnn_pred
)

lstm_mse = mean_squared_error(
    actual_lstm,
    lstm_pred
)

print("RNN MSE :", rnn_mse)
print("LSTM MSE :", lstm_mse)

plt.figure(figsize=(15,5))

plt.plot(actual_rnn,label="Actual")

plt.plot(rnn_pred,label="RNN Prediction")

plt.legend()

plt.show()

plt.figure(figsize=(15,5))

plt.plot(actual_lstm,label="Actual")

plt.plot(lstm_pred,label="LSTM Prediction")

plt.legend()

plt.show()

def build_model(hp):

    model = Sequential()

    model.add(
        LSTM(
            units=hp.Int(
                'units',
                min_value=32,
                max_value=256,
                step=32
            ),
            input_shape=(60,1)
        )
    )

    model.add(
        Dropout(
            hp.Float(
                'dropout',
                0.1,
                0.5,
                step=0.1
            )
        )
    )

    model.add(Dense(1))

    lr = hp.Choice(
        'learning_rate',
        [0.01,0.001,0.0001]
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=lr
        ),
        loss='mse'
    )

    return model

tuner = kt.RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5,
    overwrite=True,
    directory='Tesla_Tuning'
)

tuner.search(
    X_train,
    y_train,
    validation_data=(X_test,y_test),
    epochs=10
)

best_hp = tuner.get_best_hyperparameters()[0]

print(best_hp.values)

last_60 = scaled_data[-60:]

X_future = last_60.reshape(
    1,
    60,
    1
)

next_day = lstm_model.predict(X_future)

next_day = scaler.inverse_transform(next_day)

print("Next Day Price")

print(next_day)

temp_input = scaled_data[-60:].flatten().tolist()

forecast_5 = []

for i in range(5):

    x_input = np.array(
        temp_input[-60:]
    )

    x_input = x_input.reshape(
        1,
        60,
        1
    )

    pred = lstm_model.predict(
        x_input,
        verbose=0
    )

    temp_input.append(pred[0][0])

    forecast_5.append(pred[0][0])

forecast_5 = scaler.inverse_transform(
    np.array(forecast_5).reshape(-1,1)
)

print(forecast_5)

temp_input = scaled_data[-60:].flatten().tolist()

forecast_10 = []

for i in range(10):

    x_input = np.array(
        temp_input[-60:]
    )

    x_input = x_input.reshape(
        1,
        60,
        1
    )

    pred = lstm_model.predict(
        x_input,
        verbose=0
    )

    temp_input.append(pred[0][0])

    forecast_10.append(pred[0][0])

forecast_10 = scaler.inverse_transform(
    np.array(forecast_10).reshape(-1,1)
)

print(forecast_10)

temp_input = scaled_data[-60:].flatten().tolist()

forecast_10 = []

for i in range(10):

    x_input = np.array(
        temp_input[-60:]
    )

    x_input = x_input.reshape(
        1,
        60,
        1
    )

    pred = lstm_model.predict(
        x_input,
        verbose=0
    )

    temp_input.append(pred[0][0])

    forecast_10.append(pred[0][0])

forecast_10 = scaler.inverse_transform(
    np.array(forecast_10).reshape(-1,1)
)

print(forecast_10)

results = pd.DataFrame({
    "Model":["SimpleRNN","LSTM"],
    "MSE":[rnn_mse,lstm_mse],
    "RMSE":[np.sqrt(rnn_mse),np.sqrt(lstm_mse)]
})

results

df['MA30'] = df['Close'].rolling(30).mean()
df['MA100'] = df['Close'].rolling(100).mean()

plt.figure(figsize=(15,6))
plt.plot(df['Close'], label='Close')
plt.plot(df['MA30'], label='30-Day MA')
plt.plot(df['MA100'], label='100-Day MA')
plt.legend()
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df['Close'], bins=50, kde=True)
plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    range(1,6),
    forecast_5.flatten(),
    marker='o'
)

plt.title("5 Day Forecast")
plt.xlabel("Days")
plt.ylabel("Predicted Price")

plt.show()

!pip install streamlit pyngrok -q
!npm install localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Tesla Stock Price Prediction")
# 
# st.write("Streamlit is running successfully in Colab!")

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # paste full Tesla Streamlit code here

!cat /content/logs.txt

!ps -ef | grep streamlit

!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!ps -ef | grep streamlit

!curl http://localhost:8501

!npx localtunnel --port 8501

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!cloudflared tunnel --url http://localhost:8501

!ps -ef | grep streamlit

!pkill -f streamlit
!pkill -f cloudflared

!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!ps -ef | grep streamlit

!curl http://localhost:8501

!cloudflared tunnel --url http://localhost:8501

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Tesla Stock Predictor")
# st.success("App is running successfully!")

!nohup cloudflared tunnel --url http://localhost:8501 > tunnel.log 2>&1 &

!cat tunnel.log

!ps -ef | grep streamlit

!curl http://localhost:8501

!tail -50 logs.txt

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Tesla Stock Price Prediction")
# 
# st.write("Welcome to Tesla Stock Prediction Project")
# 
# name = st.text_input("Enter your name")
# 
# if name:
#     st.success(f"Hello {name}")

!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!curl http://localhost:8501

!nohup cloudflared tunnel --url http://localhost:8501 > tunnel.log 2>&1 &

!cat tunnel.log

!pkill -f streamlit

!ps -ef | grep streamlit

!curl http://localhost:8501

!tail -50 logs.txt

!pkill -f streamlit
!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!curl http://localhost:8501

!ps -ef | grep streamlit
!curl http://localhost:8501
!tail -50 logs.txt

!pkill -f cloudflared

!curl http://localhost:8501

!nohup cloudflared tunnel --url http://localhost:8501 > tunnel.log 2>&1 &

!grep trycloudflare tunnel.log

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# from tensorflow.keras.models import load_model
# import matplotlib.pyplot as plt
# 
# st.title("Tesla Stock Price Prediction")
# 
# df = pd.read_csv("TSLA.csv")
# 
# st.subheader("Dataset Preview")
# st.dataframe(df.tail())
# 
# st.subheader("Historical Closing Price")
# 
# fig = go.Figure()
# 
# fig.add_trace(
#     go.Scatter(
#         x=df.index,
#         y=df['Close'],
#         mode='lines',
#         name='Close Price'
#     )
# )
# 
# fig.add_trace(
#     go.Scatter(
#         x=df.index,
#         y=df['MA_50'],
#         mode='lines',
#         name='50-Day MA'
#     )
# )
# 
# fig.add_trace(
#     go.Scatter(
#         x=df.index,
#         y=df['MA_200'],
#         mode='lines',
#         name='200-Day MA'
#     )
# )
# 
# fig.update_layout(
#     title="Tesla Stock Price Analysis",
#     xaxis_title="Days",
#     yaxis_title="Price ($)",
#     hovermode="x unified"
# )
# 
# st.plotly_chart(fig, use_container_width=True)
# 
# # Load model
# model = load_model("Tesla_LSTM_Model.h5")
# 
# if st.button("Predict Next Day Price"):
#     st.success("Prediction logic goes here")

!pkill -f streamlit
!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!ls -lh

!ls -R Tesla_Tuning

!ls -lh Tesla_LSTM_Model.h5

!pkill -f streamlit

!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!tail -30 logs.txt

!pkill -f streamlit
!nohup streamlit run app.py --server.port 8501 > logs.txt 2>&1 &

!tail -100 logs.txt

!pkill -f cloudflared

!nohup cloudflared tunnel --url http://localhost:8501 > tunnel.log 2>&1 &

!grep -o 'https://[-a-zA-Z0-9]*\.trycloudflare\.com' tunnel.log

from google.colab import files
files.download("app.py")
files.download("TSLA.csv")
files.download("Tesla_LSTM_Model.h5")

